export function requestDetailSearchQuery(request_number: string): string {
  return `
    SELECT
      l.[id]
      ,l.[request_number]
      ,l.[loan_request_status]
      ,l.[id_agente]
      ,u1.[nombre] as nombre_agente
      ,l.[id_grupo_original]
      ,l.[id_cliente]
      ,l.[nombre_cliente]
      ,l.[apellido_paterno_cliente]
      ,l.[apellido_materno_cliente]
      ,l.[telefono_fijo_cliente]
      ,l.[telefono_movil_cliente]
      ,l.[correo_electronico_cliente]
      ,l.[ocupacion_cliente]
      ,l.[curp_cliente]
      ,l.[id_domicilio_cliente]
      ,l.[tipo_calle_cliente]
      ,l.[nombre_calle_cliente]
      ,l.[numero_exterior_cliente]
      ,l.[numero_interior_cliente]
      ,l.[colonia_cliente]
      ,l.[municipio_cliente]
      ,l.[estado_cliente]
      ,l.[cp_cliente]
      ,l.[referencias_dom_cliente]
      ,l.[id_aval]
      ,l.[nombre_aval]
      ,l.[apellido_paterno_aval]
      ,l.[apellido_materno_aval]
      ,l.[telefono_fijo_aval]
      ,l.[telefono_movil_aval]
      ,l.[correo_electronico_aval]
      ,l.[curp_aval]
      ,l.[id_domicilio_aval]
      ,l.[tipo_calle_aval]
      ,l.[nombre_calle_aval]
      ,l.[numero_exterior_aval]
      ,l.[numero_interior_aval]
      ,l.[colonia_aval]
      ,l.[municipio_aval]
      ,l.[estado_aval]
      ,l.[cp_aval]
      ,l.[referencias_dom_aval]
      ,l.[id_plazo]
      ,l.[cantidad_prestada]
      ,l.[dia_semana]
      ,l.[fecha_inicial]
      ,l.[fecha_final_estimada]
      ,l.[cantidad_pagar]
      ,l.[tasa_de_interes]
      ,l.[observaciones]
      ,l.[created_by]
      ,l.[created_date]
      ,l.[modified_by]
      ,l.[modified_date]
      ,u2.[nombre] as modified_by_name
      ,l.[closed_by]
      ,l.[closed_date]
      ,u3.[nombre] as closed_by_name
      ,l.[status_code]
      ,l.[id_loan]  

  FROM [LOAN_REQUEST] l

  LEFT JOIN [USUARIOS] u1 on u1.id = [id_agente]
  LEFT JOIN [USUARIOS] u2 on u2.id = [modified_by]
  LEFT JOIN [USUARIOS] u3 on u3.id = [closed_by]

  WHERE REQUEST_NUMBER = '${request_number}';`;
}
