export function requestDetailSearchQuery(request_number: string): string {
  return `
    SELECT [id]
      ,[request_number]
      ,[loan_request_status]
      ,[id_agente]
      ,[id_grupo_original]
      ,[id_cliente]
      ,[nombre_cliente]
      ,[apellido_paterno_cliente]
      ,[apellido_materno_cliente]
      ,[telefono_fijo_cliente]
      ,[telefono_movil_cliente]
      ,[correo_electronico_cliente]
      ,[ocupacion_cliente]
      ,[curp_cliente]
      ,[tipo_calle_cliente]
      ,[nombre_calle_cliente]
      ,[numero_exterior_cliente]
      ,[numero_interior_cliente]
      ,[colonia_cliente]
      ,[municipio_cliente]
      ,[estado_cliente]
      ,[cp_cliente]
      ,[referencias_dom_cliente]
      ,[id_aval]
      ,[nombre_aval]
      ,[apellido_paterno_aval]
      ,[apellido_materno_aval]
      ,[telefono_fijo_aval]
      ,[telefono_movil_aval]
      ,[correo_electronico_aval]
      ,[curp_aval]
      ,[tipo_calle_aval]
      ,[nombre_calle_aval]
      ,[numero_exterior_aval]
      ,[numero_interior_aval]
      ,[colonia_aval]
      ,[municipio_aval]
      ,[estado_aval]
      ,[cp_aval]
      ,[referencias_dom_aval]
      ,[id_plazo]
      ,[cantidad_prestada]
      ,[dia_semana]
      ,[fecha_inicial]
      ,[fecha_final_estimada]
      ,[cantidad_pagar]
      ,[tasa_de_interes]
      ,[observaciones]
      ,[created_by]
      ,[created_date]
      ,[modified_by]
      ,[modified_date]
      ,[closed_by]
      ,[closed_date]
      ,[status_code]
      ,[id_loan]  

  FROM [LOAN_REQUEST]

  WHERE REQUEST_NUMBER = '${request_number}'                                                     
    ;       `;
}
