org: jonathanrangel
app: yoox-serverless-api
service: login-service
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-2
  stage: dev
  apiGateway:
    shouldStartNameWithService: true
  httpApi:
    authorizers:
      authorizerFunc:
        type: request
        functionName: authorizerFunc
        identitySource:
          - $request.header.authorization
    cors:
      allowedOrigins:
        - https://www.yooxgrupofinanciero.com
        - https://development.yooxgrupofinanciero.com
        - https://staging.yooxgrupofinanciero.com
        - http://localhost:4200

functions:
  login:
    handler: ./src/user-service/login.handler
    events:
      - httpApi:
          path: /v1/login
          method: post

  tokenValidation:
    handler: ./src/authorizer/tokenValidation.handler
    events:
      - httpApi:
          path: /v1/tokenValidation
          method: get

  loan:
    handler: ./src/payments/loan.handler
    events:
      - httpApi:
          method: get
          path: /v1/loan/{id}
          authorizer:
            name: authorizerFunc

  payment:
    handler: ./src/payments/payment.handler
    events:
      - httpApi:
          method: post
          path: /v1/payment
          authorizer:
            name: authorizerFunc

  authorizerFunc:
    handler: ./src/authorizer/auth.handler

custom:
  stage: ${opt:stage, self:provider.stage}
  environment:
    NODE_ENV: ${self:custom.stage}

plugins:
  - serverless-dotenv-plugin
  - serverless-webpack
  - serverless-offline
