org: jonathanrangel
app: yoox-serverless-api
service: yoox-serverless-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-2
  apiGateway:
    shouldStartNameWithService: true

functions:
  api:
    handler: index.handler
    events:
      - httpApi:
          path: /
          method: get
# custom:
#   webpack:
#     webpackConfig: 'webpack.config.js' # Name of webpack configuration file
#     includeModules: false # Node modules configuration for packaging
#     packager: 'npm' # Packager that will be used to package your external modules
#     excludeFiles: src/**/*.test.js # Provide a glob for files to ignore

plugins:
  - serverless-dotenv-plugin
  # - serverless-plugin-webpack
  - serverless-webpack
