export const propertiesForLoanRequest = {
  cantidad_prestada: { type: 'number', minimum: 1000 },
  plazo: {
    type: 'object',
    properties: {
      name: { type: 'string' },
      value: { type: 'string' },
      id: { type: 'integer' },
    },
  },
  fecha_inicial: { type: 'string', format: 'date-time' },
  fecha_final_estimada: { type: 'string', format: 'date-time' },
  formCliente: {
    type: 'object',
    properties: {
      nombre_cliente: { type: 'string' },
      apellido_paterno_cliente: { type: 'string' },
      apellido_materno_cliente: { type: 'string' },
      telefono_fijo_cliente: {
        type: 'string',
        pattern: '^\\d{10}$',
      },
      telefono_movil_cliente: {
        type: 'string',
        pattern: '^\\d{10}$',
      },
      curp_cliente: {
        type: 'string',
        pattern:
          '^([A-Z][AEIOUX][A-Z]{2}\\d{2}(?:0[1-9]|1[0-2])(?:0[1-9]|[12]\\d|3[01])[HM](?:AS|B[CS]|C[CLMSH]|D[FG]|G[TR]|HG|JC|M[CNS]|N[ETL]|OC|PL|Q[TR]|S[PLR]|T[CSL]|VZ|YN|ZS)[B-DF-HJ-NP-TV-Z]{3}[A-Z\\d])(\\d)$',
      },
      tipo_calle_cliente: {
        type: 'object',
        properties: {
          name: { type: 'string' },
          value: {
            type: 'string',
            enum: [
              'CALLE',
              'AVENIDA',
              'PROLONGACION',
              'CARRETERA',
              'PRIVADA',
              'BOULEVARD',
            ],
          },
        },
      },
      nombre_calle_cliente: { type: 'string' },
      numero_exterior_cliente: { type: 'string' },
      numero_interior_cliente: { type: 'string' },
      colonia_cliente: { type: 'string' },
      municipio_cliente: { type: 'string' },
      estado_cliente: {
        type: 'object',
        properties: {
          name: { type: 'string' },
          value: {
            type: 'string',
            enum: [
              'JALISCO',
              'AGUASCALIENTES',
              'BAJA CALIFORNIA',
              'BAJA CALIFORNIA SUR',
              'CAMPECHE',
              'COAHUILA',
              'COLIMA',
              'CHIAPAS',
              'CHIHUAHUA',
              'DURANGO',
              'CDMX',
              'GUANAJUATO',
              'GUERRERO',
              'HIDALGO',
              'ESTADO DE MEXICO',
              'MICHOACAN',
              'MORELOS',
              'NAYARIT',
              'NUEVO LEON',
              'OAXACA',
              'PUEBLA',
              'QUERETARO',
              'QUINTANA ROO',
              'SAN LUIS POTOSI',
              'SINALOA',
              'SONORA',
              'TABASCO',
              'TAMAULIPAS',
              'TLAXCALA',
              'VERACRUZ',
              'YUCATAN',
              'ZACATECAS',
            ],
          },
        },
      },
      cp_cliente: { type: 'string', pattern: '^\\d{5}$' },
      correo_electronico_cliente: {
        type: 'string',
        pattern: '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$',
      },
      ocupacion_cliente: { type: 'string' },
      referencias_cliente: { type: 'string' },
      observaciones_cliente: { type: 'string' },
    },
    required: [
      'nombre_cliente',
      'apellido_paterno_cliente',
      'apellido_materno_cliente',
      'telefono_fijo_cliente',
      'telefono_movil_cliente',
      'curp_cliente',
      'tipo_calle_cliente',
      'nombre_calle_cliente',
      'numero_exterior_cliente',
      'numero_interior_cliente',
      'colonia_cliente',
      'municipio_cliente',
      'estado_cliente',
      'cp_cliente',
    ],
    additionalProperties: false,
  },
  formAval: {
    type: 'object',
    properties: {
      nombre_cliente: { type: 'string' },
      apellido_paterno_cliente: { type: 'string' },
      telefono_fijo: {
        type: 'string',
        pattern: '^\\d{10}$',
      },
      telefono_movil: {
        type: 'string',
        pattern: '^\\d{10}$',
      },
      correo_electronico_cliente: {
        type: 'string',
        pattern: '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$',
      },
      ocupacion: { type: 'string' },
      curp_cliente: {
        type: 'string',
        pattern:
          '^([A-Z][AEIOUX][A-Z]{2}\\d{2}(?:0[1-9]|1[0-2])(?:0[1-9]|[12]\\d|3[01])[HM](?:AS|B[CS]|C[CLMSH]|D[FG]|G[TR]|HG|JC|M[CNS]|N[ETL]|OC|PL|Q[TR]|S[PLR]|T[CSL]|VZ|YN|ZS)[B-DF-HJ-NP-TV-Z]{3}[A-Z\\d])(\\d)$',
      },
      apellido_materno_cliente: { type: 'string' },
      tipo_calle_cliente: {
        type: 'object',
        properties: {
          name: { type: 'string' },
          value: {
            type: 'string',
            enum: [
              'CALLE',
              'AVENIDA',
              'PROLONGACION',
              'CARRETERA',
              'PRIVADA',
              'BOULEVARD',
            ],
          },
        },
      },
      nombre_calle_cliente: { type: 'string' },
      numero_exterior_cliente: { type: 'string' },
      numero_interior_cliente: { type: 'string' },
      colonia_cliente_cliente: { type: 'string' },
      municipio_cliente: { type: 'string' },
      estado_cliente: {
        type: 'object',
        properties: {
          name: { type: 'string' },
          value: {
            type: 'string',
            enum: [
              'JALISCO',
              'AGUASCALIENTES',
              'BAJA CALIFORNIA',
              'BAJA CALIFORNIA SUR',
              'CAMPECHE',
              'COAHUILA',
              'COLIMA',
              'CHIAPAS',
              'CHIHUAHUA',
              'DURANGO',
              'CDMX',
              'GUANAJUATO',
              'GUERRERO',
              'HIDALGO',
              'ESTADO DE MEXICO',
              'MICHOACAN',
              'MORELOS',
              'NAYARIT',
              'NUEVO LEON',
              'OAXACA',
              'PUEBLA',
              'QUERETARO',
              'QUINTANA ROO',
              'SAN LUIS POTOSI',
              'SINALOA',
              'SONORA',
              'TABASCO',
              'TAMAULIPAS',
              'TLAXCALA',
              'VERACRUZ',
              'YUCATAN',
              'ZACATECAS',
            ],
          },
        },
      },
      cp_cliente: { type: 'string', pattern: '^\\d{5}$' },
      referencias: { type: 'string' },
      additionalProperties: false,
    },
  },
  id: { type: 'integer' },
  request_number: { type: 'string' },
  loan_request_status: {
    type: 'string',
    enum: ['EN REVISION', 'ACTUALIZAR', 'APROBADO', 'RECHAZADO'],
  },
  id_agente: { type: 'integer' },
  id_grupo_original: { type: 'integer' },
  id_cliente: { type: 'integer' },
  dia_semana: {
    type: 'string',
    enum: [
      'DOMINGO',
      'LUNES',
      'MARTES',
      'MIERCOLES',
      'JUEVES',
      'VIERNES',
      'SABADO',
    ],
  },
  cantidad_pagar: { type: 'number' },
  tasa_interes: { type: 'integer' },
  created_by: { type: 'integer' },
  created_date: { type: 'string', format: 'date-time' },
  modified_date: { type: 'string', format: 'date-time' },
  closed_by: { type: 'integer' },
  closed_date: { type: 'string', format: 'date-time' },
  status_code: { type: 'integer' },
};

export const requiredFielsForUpdateLoanRequest = [
  'id',
  'request_number',
  'loan_request_status',
  'id_agente',
  'id_grupo_original',
  'nombre_cliente',
  'apellido_paterno_cliente',
  'apellido_materno_cliente',
  'telefono_fijo',
  'telefono_movil',
  'curp',
  'tipo_calle',
  'nombre_calle',
  'numero_exterior',
  'numero_interior',
  'colonia',
  'municipio',
  'estado',
  'cp',
  'id_plazo',
  'cantidad_prestada',
  'dia_semana',
  'fecha_inicial',
  'fecha_final_estimada',
  'cantidad_pagar',
  'tasa_interes',
];
