export const propertiesForLoanRequest = {
  id: { type: 'integer' },
  request_number: { type: 'string' },
  loan_request_status: {
    type: 'string',
    enum: ['EN REVISION', 'ACTUALIZAR', 'APROBADO', 'RECHAZADO'],
  },
  id_agente: { type: 'integer' },
  id_grupo_original: { type: 'integer' },
  id_cliente: { type: 'integer' },
  nombre_cliente: { type: 'string' },
  apellido_paterno_cliente: { type: 'string' },
  apellido_materno_cliente: { type: 'string' },
  telefono_fijo: {
    type: 'string',
    pattern: '^\\d{10}$',
  },
  telefono_movil: {
    type: 'string',
    pattern: '^\\d{10}$',
  },
  correo_electronico: {
    type: 'string',
    pattern: '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$',
  },
  ocupacion: { type: 'string' },
  curp: {
    type: 'string',
    pattern:
      '^([A-Z][AEIOUX][A-Z]{2}\\d{2}(?:0[1-9]|1[0-2])(?:0[1-9]|[12]\\d|3[01])[HM](?:AS|B[CS]|C[CLMSH]|D[FG]|G[TR]|HG|JC|M[CNS]|N[ETL]|OC|PL|Q[TR]|S[PLR]|T[CSL]|VZ|YN|ZS)[B-DF-HJ-NP-TV-Z]{3}[A-Z\\d])(\\d)$',
  },
  tipo_calle: {
    type: 'string',
    enum: [
      'CALLE',
      'AVENIDA',
      'PROLONGACION',
      'CARRETERA',
      'PRIVADA',
      'BOULEVARD',
    ],
  },
  nombre_calle: { type: 'string' },
  numero_exterior: { type: 'string' },
  numero_interior: { type: 'string' },
  colonia: { type: 'string' },
  municipio: { type: 'string' },
  estado: {
    type: 'string',
    enum: [
      'JALISCO',
      'AGUASCALIENTES',
      'BAJA CALIFORNIA',
      'BAJA CALIFORNIA SUR',
      'CAMPECHE',
      'COAHUILA',
      'COLIMA',
      'CHIAPAS',
      'CHIHUAHUA',
      'DURANGO',
      'CDMX',
      'GUANAJUATO',
      'GUERRERO',
      'HIDALGO',
      'MEXICO',
      'MICHOACAN',
      'MORELOS',
      'NAYARIT',
      'NUEVO LEON',
      'OAXACA',
      'PUEBLA',
      'QUERETARO',
      'QUINTANA ROO',
      'SAN LUIS POTOSI',
      'SINALOA',
      'SONORA',
      'TABASCO',
      'TAMAULIPAS',
      'TLAXCALA',
      'VERACRUZ',
      'YUCATAN',
      'ZACATECAS',
    ],
  },
  cp: { type: 'string', pattern: '^\\d{5}$' },
  referencias: { type: 'string' },
  id_plazo: { type: 'integer' },
  cantidad_prestada: { type: 'number', minimum: 1000 },
  dia_semana: {
    type: 'string',
    enum: [
      'DOMINGO',
      'LUNES',
      'MARTES',
      'MIERCOLES',
      'JUEVES',
      'VIERNES',
      'SABADO',
    ],
  },
  fecha_inicial: { type: 'string', format: 'date-time' },
  fecha_final_estimada: { type: 'string', format: 'date-time' },
  cantidad_pagar: { type: 'number' },
  tasa_interes: { type: 'integer' },
  observaciones: { type: 'string' },
  created_by: { type: 'integer' },
  created_date: { type: 'string', format: 'date-time' },
  modified_date: { type: 'string', format: 'date-time' },
  closed_by: { type: 'integer' },
  closed_date: { type: 'string', format: 'date-time' },
  status_code: { type: 'integer' },
};

export const requiredFielsForNewLoanRequest = [
  'id_agente',
  'id_grupo_original',
  'nombre_cliente',
  'apellido_paterno_cliente',
  'apellido_materno_cliente',
  'telefono_fijo',
  'telefono_movil',
  'curp',
  'tipo_calle',
  'nombre_calle',
  'numero_exterior',
  'numero_interior',
  'colonia',
  'municipio',
  'estado',
  'cp',
  'id_plazo',
  'cantidad_prestada',
  'dia_semana',
  'fecha_inicial',
  'fecha_final_estimada',
  'cantidad_pagar',
  'tasa_interes',
  'created_by',
];

export const requiredFielsForUpdateLoanRequest = [
  'id',
  'request_number',
  'loan_request_status',
  'id_agente',
  'id_grupo_original',
  'nombre_cliente',
  'apellido_paterno_cliente',
  'apellido_materno_cliente',
  'telefono_fijo',
  'telefono_movil',
  'curp',
  'tipo_calle',
  'nombre_calle',
  'numero_exterior',
  'numero_interior',
  'colonia',
  'municipio',
  'estado',
  'cp',
  'id_plazo',
  'cantidad_prestada',
  'dia_semana',
  'fecha_inicial',
  'fecha_final_estimada',
  'cantidad_pagar',
  'tasa_interes',
];
